% When m=0,n=1, the code for Equation (46).
function posimn01=posimn01(rD,RD,z,omega,lambda)
posimn01=((1./rD).*sinh(sqrt(z.*g(z,omega,lambda)).*rD)).*((1./(-(RD)^2)).*cosh(sqrt(z.*g(z,omega,lambda)).*RD)+(1/RD).*sqrt(z.*g(z,omega,lambda))...
        .*sinh(sqrt(z.*g(z,omega,lambda)).*RD))-((1./rD).*cosh(sqrt(z.*g(z,omega,lambda)).*rD)).*((1./(-(RD)^2)).*sinh(sqrt(z.*g(z,omega,lambda)).*RD)...
         +(1./RD).*sqrt(z.*g(z,omega,lambda)).*cosh(sqrt(z.*g(z,omega,lambda)).*RD));
